language: rust

rust:
    - nightly

script:
    - cargo doc
    - cargo build -v

sudo: true

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    ./publish.sh
