sudo: false
language: rust
cache: cargo
branches:
  only:
    - staging
    - trying
    - develop
    - master
addons:
  apt:
    packages:
      - libasound2-dev
rust:
    - stable
    - beta
    - nightly
script:
    - cargo test --verbose

