language: rust

rust:
    - nightly
    - stable

script:
    - cargo doc --no-deps
    - cargo build -v

sudo: true

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    ./publish.sh
