sudo: false
language: rust
cache: cargo
branches:
  only:
    - staging
    - trying
    - develop
    - master
addons:
  apt:
    packages:
      - libasound2-dev
rust:
  - stable
  - beta
  - nightly

stages:
  - check formatting
  - lint
  - test

jobs:
  include:
    - stage: check formatting
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
    - stage: lint
      rust: stable
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all-targets --all-features --verbose -- -D warnings

script:
  - cargo test --all
