[package]
name = "amethyst_cli"
version = "0.1.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "Command-line interface for managing Amethyst projects"
keywords = ["game", "engine", "cli", "tool", "amethyst"]

repository = "https://github.com/ebkalderon/amethyst_cli"

readme = "README.md"
license = "GPL-3.0"

[[bin]]
name = "amethyst"
path = "src/main.rs"

[dependencies]
clap = "1.5.5"
toml = "0.1"
