[package]
name = "amethyst_tools"
version = "0.5.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "Game development tools for the Amethyst engine"
keywords = ["game", "engine", "tool", "editor", "amethyst"]

repository = "https://github.com/ebkalderon/amethyst_tools"

readme = "README.md"
license = "MIT/Apache-2.0"

include = ["src/**", "template/**", "Cargo.toml", "build.rs", "LICENSE-*", "README.md"]
build = "build.rs"

[lib]
name = "amethyst_cli"
path = "src/lib.rs"

[[bin]]
name = "amethyst"
path = "src/main.rs"

[dependencies]
clap = "2"

[build-dependencies]
ron = "0.1.3"
